server:
  port: 8766 # 项目端口

spring:
  application:
    name: cloud-zull #项目名称 唯一性

eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    eureka-client:
      path: /eureka-client/**
      serviceId: eureka-client
    cloud-riboon:
          path: /cloud-riboon/**
          serviceId: cloud-riboon
    cloud-feign:
          path: /cloud-feign/**
          serviceId: cloud-feign
