server:
  port: 8765 # 项目端口

spring:
  application:
    name: cloud-feign #项目名称 唯一性

eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true #开启断路器功能
