spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  application:
    name: dept-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo              # 数据库名称
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                   # 等待连接获取的最大超时时间

---
server:
  port: 8001
spring:
  application:
    name: dept-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo              # 数据库名称
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                   # 等待连接获取的最大超时时间



mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.springcloud.entity              # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      #defaultZone:  http://localhost:9000/eureka
      defaultZone:  http://localhost:9000/eureka,http://localhost:9001/eureka,http://localhost:9002/eureka
  #instance:
    # prefer-ip-address: true  # 显示id地址 2.x之后默认显示IP地址 2.0以前版本不显示
    # instance-id: dept-provider  # 注册中心显示的名称    2.x默认 ip:serviceName:port  2.0之前版本是电脑名称：serviceName:port

info:
  app.name: dept-provider
  company.name: dept-provider
  build.artifactId: dept-provider
  build.version: 1.0.0
  app.port: 9001
  a: 1
  b: b
management:
  endpoints:
    web:
      exposure:
        include: '*'
